--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#010101"
foreground="#ffffff"
cursor="#ff5995"

-- Colors
color0="#1b1d1e"
color1="#f92672"
color2="#82b414"
color3="#fd971f"
color4="#4e82aa"
color5="#8c54fe"
color6="#465457"
color7="#ccccc6"
color8="#505354"
color9="#f92672"
color10="#82b414"
color11="#fd971f"
color12="#4e82aa"
color13="#8c54fe"
color14="#465457"
color15="#ccccc6"
