# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#010101'
foreground='#ffffff'
cursor='#ff5995'

# Colors
color0='#1b1d1e'
color1='#f92672'
color2='#82b414'
color3='#fd971f'
color4='#4e82aa'
color5='#8c54fe'
color6='#465457'
color7='#ccccc6'
color8='#505354'
color9='#f92672'
color10='#82b414'
color11='#fd971f'
color12='#4e82aa'
color13='#8c54fe'
color14='#465457'
color15='#ccccc6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
